--	1번. MEMBER
DROP TABLE MEMBER;
DROP TABLE authorities_member;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(500) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_PHONE VARCHAR2(500) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(4000) NOT NULL,
	MEMBER_SUBWAY VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ENABLED INTEGER NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NOT NULL,
	MEMBER_REGDATE DATE NOT NULL,
	MEMBER_PW_CHANGE DATE
);

COMMENT ON TABLE MEMBER is '회원';
COMMENT ON COLUMN MEMBER.MEMBER_ID is '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW is '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_ENABLED is '계정사용여부';

CREATE TABLE authorities_member(
	MEMBER_ID VARCHAR2(500) NOT NULL,
	authority VARCHAR2(20) NOT NULL
);

COMMENT ON TABLE authorities_member is '권한';
COMMENT ON COLUMN authorities_member.MEMBER_ID is '회원아이디';
COMMENT ON COLUMN authorities_member.authority is '권한';

ALTER TABLE authorities_member ADD CONSTRAINT IDX_authorities_member_PK PRIMARY KEY (MEMBER_ID, authority);
ALTER TABLE authorities_member ADD CONSTRAINT IDX_authorities_member_FK0 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);

-- 관리자를 추가하한다. 추가할 때 이메일을 개인 이메일로 하여 insert한다
-- 홈페이지에서 비밀번호 찾기를 통해 비밀번호를 바꾼다.
INSERT INTO MEMBER VALUES ('admin', '1','관리자','010-2222-1111','서울','강남역','jaewon9937@gmail.com',1,'admin',sysdate,sysdate);

INSERT INTO authorities_member (MEMBER_ID, authority) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO authorities_member (MEMBER_ID, authority) VALUES ('admin', 'ROLE_USER');

--	2번 도시락테이블
DROP TABLE DOSIRAK;
DROP SEQUENCE DOSIRAK_POSTNUM;

CREATE SEQUENCE DOSIRAK_POSTNUM;

CREATE TABLE DOSIRAK(
   DOSIRAK_POSTNUM NUMBER PRIMARY KEY,		-- 도시락 번호
   DOSIRAK_NAME VARCHAR2(100) NOT NULL,		-- 도시락 이름
   DOSIRAK_TITLE VARCHAR2(2000) NOT NULL,	-- 제목
   DOSIRAK_CONTENT VARCHAR2(4000) NOT NULL,	-- 내용
   DOSIRAK_DELIVERY VARCHAR2(100) NOT NULL,	-- 주문시간
   DOSIRAK_PRICE NUMBER NOT NULL,			-- 가격
   DOSIRAK_NUM NUMBER NOT NULL,				-- 갯수
   DOSIRAK_AFTERNUM NUMBER,					-- 주문량
   DOSIRAK_VIEWS NUMBER,					-- 조회수
   TAN NUMBER NOT NULL,						-- 탄수화물
   DAN NUMBER NOT NULL,						-- 단백질
   GI NUMBER NOT NULL,						-- 지방
   KCAL NUMBER NOT NULL,					-- 칼로리
   MAINIMAGE CLOB,							-- 메인이미지
   THUMBNAIL CLOB,						-- 썸네일이미지
   DOSIRAK_REGDATE DATE NOT NULL			-- 날짜
);

--	3번 이벤트게시판
DROP TABLE EVENTBOARD;
DROP SEQUENCE EVENT_POSTNUM;

CREATE SEQUENCE EVENT_POSTNUM ;

CREATE TABLE EVENTBOARD(
	EVENT_POSTNUM NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	
	EVENT_TITLE CLOB NOT NULL,
	EVENT_CONTENT CLOB NOT NULL,
	EVENT_VIEWS NUMBER NOT NULL,
	EVENT_REGDATE DATE NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NULL
);

--	4번. 자유게시판
DROP TABLE FREEBOARD;
DROP SEQUENCE FREE_POSTNUM;

CREATE SEQUENCE FREE_POSTNUM ;

CREATE TABLE FREEBOARD(
	FREE_POSTNUM NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) ,
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	FREE_TITLE VARCHAR2(1000) NOT NULL,
	FREE_CONTENT VARCHAR2(4000) NOT NULL,
	FREE_VIEWS NUMBER NOT NULL,
	FREE_REGDATE DATE NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NULL
);

--	5번. 자유게시판 댓글
DROP TABLE COM_BOARD;

DROP SEQUENCE COM_NUMSEQ;
DROP SEQUENCE COM_COMNOSEQ;
DROP SEQUENCE COM_COMNO;

CREATE SEQUENCE COM_NUMSEQ;
CREATE SEQUENCE COM_COMNO;

CREATE TABLE COM_BOARD(
	COM_NUM NUMBER PRIMARY KEY, -- comment = com으로 줄임
	FREE_POSTNUM NUMBER, -- 항상 free 보드의 키를 가지고 값니다.
	MEMBER_ID VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(200),
	COM_CONTENT VARCHAR2(2000) NOT NULL,
	COM_CONTAB NUMBER, -- 대댓글 contentTAB 주기
	COM_COMNO NUMBER , --그룹 대신 com_comno  // 댓글번호
	COM_COMSQ NUMBER ,  -- 댓글도 여러개 달릴수 있으니깐요 댓글에서의 순번입니다.  //댓글 순서
	COM_REGDATE DATE
);

--	6번. 공지사항 게시판
DROP TABLE NOTICEBOARD;
DROP SEQUENCE NOTICESEQ;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICEBOARD(
NOTICE_POSTNUM NUMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(500) NOT NULL,
NOTICE_TITLE VARCHAR2(500) NOT NULL,
NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
NOTICE_REGDATE DATE NOT NULL,
NOTICE_VIEWS NUMBER
);

--	실행 전에 이 INSERT 문 한개는 꼭 추가해줘야 한다.
INSERT INTO NOTICEBOARD VALUES (NOTICESEQ.NEXTVAL, 'admin','TEST', 'TEST1234',SYSDATE,0);

--	7번. 오더테이블
DROP TABLE BOXORDER;
DROP SEQUENCE ORDERSEQ;

CREATE SEQUENCE ORDERSEQ;

CREATE TABLE BOXORDER(
	ORDERSEQ NUMBER NOT NULL,
	ORDERNUMBER VARCHAR2(1000) NOT NULL,
	MEMBER_ID VARCHAR2(500) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NOT NULL,
	DOSIRAK_TITLE VARCHAR2(2000),
	DOSIRAK_DELIVERY VARCHAR2(100) NOT NULL,
	DOSIRAK_PRICE NUMBER,
	GET_NAME VARCHAR2(500),
	GET_PHONE VARCHAR2(500),
	GET_SUBWAY VARCHAR2(500),
	DISH1 VARCHAR2(100),
	DISH2 VARCHAR2(100),
	DISH3 VARCHAR2(100),
	DISH4 VARCHAR2(100),
	DISH5 VARCHAR2(100),
	DISH6 VARCHAR2(100),
	DISH7 VARCHAR2(100),
	TAN NUMBER NOT NULL,
	DAN NUMBER NOT NULL,
	GI NUMBER NOT NULL,
	KCAL NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	ORDER_REGDATE DATE NOT NULL,
	QRCODE VARCHAR2(4000),
	RECEIVECHK VARCHAR2(10) NOT NULL,
	CUSTOM_STATUS VARCHAR2(2) NOT NULL
);

--	8번. 예약테이블
DROP TABLE RESERVATION;

CREATE SEQUENCE RESERVATIONSEQ;

CREATE TABLE RESERVATION(
	RESERVATIONSEQ NUMBER NOT NULL,
	DAYOFWEEK VARCHAR2(100) NOT NULL,
	RES_REGDATE DATE,
	ORDER_STATUS VARCHAR2(10) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ID VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NOT NULL,
	DOSIRAK_TITLE VARCHAR2(2000),
	DOSIRAK_DELIVERY VARCHAR2(100) NOT NULL,
	DOSIRAK_PRICE NUMBER,
	DISH1 VARCHAR2(100),
	DISH2 VARCHAR2(100),
	DISH3 VARCHAR2(100),
	DISH4 VARCHAR2(100),
	DISH5 VARCHAR2(100),
	DISH6 VARCHAR2(100),
	DISH7 VARCHAR2(100),
	TAN NUMBER NOT NULL,
	DAN NUMBER NOT NULL,
	GI NUMBER NOT NULL,
	KCAL NUMBER NOT NULL,
	CUSTOM_STATUS VARCHAR2(2) NOT NULL
);

--9번.	업로드 테이블
DROP TABLE UPLOAD_TABLE;
DROP SEQUENCE UPLOAD_SEQ;

CREATE SEQUENCE UPLOAD_SEQ;

CREATE TABLE UPLOAD_TABLE(
	UPLOAD_NO NUMBER NOT NULL PRIMARY KEY,
	DISH_NAME VARCHAR2(300) NOT NULL,
	DISH_TAN VARCHAR2(300) NOT NULL,
	DISH_DAN VARCHAR2(300) NOT NULL,
	DISH_ZI VARCHAR2(300) NOT NULL,
	DISH_AMOUNT VARCHAR2(300) NOT NULL,
	DISH_CAL VARCHAR2(300) NOT NULL,
	DISH_KIND VARCHAR2(300) NOT NULL,
	FILE_NAME VARCHAR2(500) NOT NULL,
	FILE_PATH VARCHAR2(4000) NOT NULL
);
