DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(500) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_PHONE VARCHAR2(500) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(4000) NOT NULL,
	MEMBER_SUBWAY VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NOT NULL,
	MEMBER_REGDATE DATE NOT NULL
);

SELECT * FROM MEMBER;

DELETE FROM MEMBER WHERE MEMBER_ID = 'qq';

INSERT INTO MEMBER VALUES ('admin', 'admin', '정민호', '010-4933-2976', '경기도 성남시', '복정역', '1212081@naver.com', 'Y', 'admin' ,SYSDATE);


UPDATE MEMBER SET MEMBER_PW = '2222', MEMBER_PHONE = '1111', MEMBER_EMAIL = '1111',
		MEMBER_ADDRESS = '1111', MEMBER_SUBWAY = '1111' 
		WHERE MEMBER_ID = 'admin'