DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(500) PRIMARY KEY,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE VARCHAR2(500) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(4000) NOT NULL,
	MEMBER_SUBWAY VARCHAR2(4000) NOT NULL,
	MEMBER_ENABLED VARCHAR2(2) NOT NULL,
	MEMBER_LEVEL VARCHAR2(100) NOT NULL,
	MEMBER_REGDATE DATE NOT NULL
);

SELECT * FROM MEMBER; 

DELETE FROM MEMBER WHERE member_id = 'ㅁㅁ';

INSERT INTO MEMBER VALUES ('admin', 'admin', '관리자' , 'admin@admin.com', '010-1111-1111', '서울 강남구', '작전역','Y' ,'ADMIN', SYSDATE);
INSERT INTO MEMBER VALUES ('jaewon', '1111', '황재원' , 'jaewon@jaewon.com', '010-2222-2222', '인천 계양구' ,'계산역','Y', 'USER',SYSDATE);
