DROP TABLE DOSIRAK;
DROP SEQUENCE DOSIRAK_POSTNUM;

CREATE SEQUENCE DOSIRAK_POSTNUM;
CREATE TABLE DOSIRAK(
   DOSIRAK_POSTNUM NUMBER PRIMARY KEY,
   DOSIRAK_NAME VARCHAR2(100) NOT NULL,
   DOSIRAK_TITLE VARCHAR2(2000) NOT NULL,
   DOSIRAK_CONTENT VARCHAR2(4000) NOT NULL,
   DOSIRAK_DELIVERY VARCHAR2(100) NOT NULL,
   DOSIRAK_PRICE NUMBER NOT NULL,
   DOSIRAK_NUM NUMBER NOT NULL,
   DOSIRAK_AFTERNUM NUMBER,
   DOSIRAK_VIEWS NUMBER NOT NULL,
   TAN NUMBER NOT NULL,
   DAN NUMBER NOT NULL,
   GI NUMBER NOT NULL,
   KCAL NUMBER NOT NULL,
   MAINIMAGE CLOB,
   THUMBNAIL CLOB,
   DOSIRAK_REGDATE DATE NOT NULL
);

SELECT * FROM DOSIRAK;

--SELECT * FROM DOSIRAK (SELECT ROWNUM AS RN, B.*
--FROM (SELECT * FROM DOSIRAK ORDER BY DOSIRAK_POSTNUM DESC) B)
--WHERE RN BETWEEN 1 AND 9

 
INSERT INTO DOSIRAK
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락8','건강도시락TITLE8','CONTENT내용8',
'PM',4500,1,0,0,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);

INSERT INTO DOSIRAK
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락9','건강도시락TITLE9','CONTENT내용9',
'AM',4500,1,0,0,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);

INSERT INTO DOSIRAK
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락10','건강도시락TITLE10','CONTENT내용10',
'PM',4500,1,0,0,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);

INSERT INTO DOSIRAK
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락11','건강도시락TITLE11','CONTENT내용11',
'AM',4500,1,0,0,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);

INSERT INTO DOSIRAK
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락12','건강도시락TITLE12','CONTENT내용12',
'PM',4500,1,0,0,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);


INSERT INTO DOSIRAK 
VALUES(DOSIRAK_POSTNUM.NEXTVAL,'건강도시락15','건강도시락TITLE15','CONTENT내용15',
'PM',5500,1,21,200,300,400,555,'MAINIMAGE','THUMBNAIL',SYSDATE);

SELECT * FROM (SELECT * FROM DOSIRAK ORDER BY DOSIRAK_VIEWS DESC) WHERE ROWNUM<=3

DELETE FROM DOSIRAK;