DROP TABLE EVENTBOARD;
DROP SEQUENCE EVENT_POSTNUM;

--이벤트글글 번호 시퀀스
CREATE SEQUENCE EVENT_POSTNUM ;

CREATE TABLE EVENTBOARD(
	EVENT_POSTNUM NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	
	EVENT_TITLE CLOB NOT NULL,
	EVENT_CONTENT CLOB NOT NULL,
	EVENT_VIEWS NUMBER NOT NULL,
	EVENT_REGDATE DATE NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NULL
);

INSERT INTO EVENTBOARD VALUES(EVENT_POSTNUM.NEXTVAL,'romantic_coding','YUMI','이벤트글글입니다.1','1글 내용입니다.', 0, SYSDATE, '회원');
INSERT INTO EVENTBOARD VALUES(EVENT_POSTNUM.NEXTVAL,'romantic_coding','YUMI','이벤트글글입니다.2','2글 내용입니다.', 1, SYSDATE, '회원');
INSERT INTO EVENTBOARD VALUES(EVENT_POSTNUM.NEXTVAL,'romantic_coding','YUMI','이벤트글글입니다.3','3글 내용입니다.', 2, SYSDATE, '회원');
INSERT INTO EVENTBOARD VALUES(EVENT_POSTNUM.NEXTVAL,'romantic_coding','YUMI','이벤트글글입니다.4','4글 내용입니다.', 1, SYSDATE, '회원');
INSERT INTO EVENTBOARD VALUES(EVENT_POSTNUM.NEXTVAL,'romantic_coding','YUMI','이벤트글글입니다.5','5글 내용입니다.', 0, SYSDATE, '회원');

SELECT * FROM EVENTBOARD 
 ORDER BY EVENT_POSTNUM DESC;

SELECT * FROM EVENTBOARD;


DELETE FROM EVENTBOARD;


