
DROP TABLE COM_BOARD;

DROP SEQUENCE COM_NUMSEQ;
DROP SEQUENCE COM_COMNOSEQ;
DROP SEQUENCE COM_COMNO;
-- 글 번호 시퀀스
CREATE SEQUENCE COM_NUMSEQ;

--댓글 번호 시퀀스
CREATE SEQUENCE COM_COMNO;

CREATE TABLE COM_BOARD(
	COM_NUM NUMBER PRIMARY KEY, -- comment = com으로 줄임
	FREE_POSTNUM NUMBER, -- 항상 free 보드의 키를 가지고 값니다.
	MEMBER_ID VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(200),
	COM_CONTENT VARCHAR2(2000) NOT NULL,
	COM_CONTAB NUMBER, -- 대댓글 contentTAB 주기
	COM_COMNO NUMBER NOT NULL, --그룹 대신 com_comno  // 댓글번호
	COM_COMSQ NUMBER ,  -- 댓글도 여러개 달릴수 있으니깐요 댓글에서의 순번입니다.  //댓글 순서
	COM_REGDATE DATE

);




	
SELECT * FROM COM_BOARD WHERE COM_NUM = 1
 ORDER BY COM_COMNO DESC, COM_COMSQ;

 
 select nvl(max(COM_COMSQ)+1,1) as COM_COMSQ from COM_BOARD
where 1=1
and FREE_POSTNUM = 63
;


INSERT INTO COM_BOARD VALUES(COM_NUMSEQ.NEXTVAL,63,'yumi','홍유미',' 첫번째 답글입니다. ',0,COM_COMNO.NEXTVAL,1,SYSDATE);

INSERT INTO COM_BOARD VALUES(COM_NUMSEQ.NEXTVAL,63,'yumi','홍유미',' 두번째 답글입니다. ',0,  
		(select nvl(max(COM_COMSQ)+1,1) as COM_COMSQ from COM_BOARD
		where 1=1
		and FREE_POSTNUM = 63)
	,1,SYSDATE);
	



SELECT * FROM COM_BOARD;



--두번째 글에 답변 작성
-- 그룹번호 유지, 그룹순서 +1 TITLETAB+1
 INSERT INTO COM_BOARD VALUES(COMMENTSEQ.NEXTVAL,
	1,1,'yumi','답글 테스트입니다.',
	(SELECT COM_COMNO FROM COM_BOARD WHERE COM_NUM = 1),
	(SELECT COM_COMSQ FROM COM_BOARD WHERE COMMENT_NUM = 1)+ 1,
	(SELECT COM_CONTAB FROM COM_BOARD WHERE COM_NUM = 1 )+ 1, 'N' );


