DROP TABLE FREEBOARD;
DROP TABLE FREE_POSTNUM;

--게시글 번호 시퀀스
CREATE SEQUENCE FREE_POSTNUM ;

CREATE TABLE FREEBOARD(
	MEMBER_ID VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	FREE_TITLE VARCHAR2(1000) NOT NULL,
	FREE_CONTENT VARCHAR2(4000) NOT NULL,
	FREE_VIEWS NUMBER NOT NULL,
	FREE_REGDATE DATE NOT NULL,
	MEMBER_LEVEL VARCHAR2(200) NOT NULL	
);

INSERT INTO FREEBOARD VALUES('낭만코딩','YUMI','게시글입니다.','글 내용입니다.', 0, SYSDATE, '회원');

SELECT * FROM FREEBOARD;


DELETE FROM FREEBOARD;