DROP TABLE FREEBOARD;
DROP SEQUENCE FREE_POSTNUM;

--게시글 번호 시퀀스
CREATE SEQUENCE FREE_POSTNUM ;

CREATE TABLE FREEBOARD(
	FREE_POSTNUM NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) ,
	MEMBER_NAME VARCHAR2(200) NOT NULL,
	FREE_TITLE VARCHAR2(1000) NOT NULL,
	FREE_CONTENT VARCHAR2(4000) NOT NULL,
	FREE_VIEWS NUMBER NOT NULL,
	FREE_REGDATE DATE NOT NULL,
	MEMBER_LEVEL VARCHAR2(200) NULL
);

INSERT INTO FREEBOARD VALUES(FREE_POSTNUM.NEXTVAL,'romantic_coding','YUMI','게시글입니다.1','1글 내용입니다.', 0, SYSDATE, '회원');
INSERT INTO FREEBOARD VALUES(FREE_POSTNUM.NEXTVAL,'romantic_coding','YUMI','게시글입니다.2','2글 내용입니다.', 1, SYSDATE, '회원');
INSERT INTO FREEBOARD VALUES(FREE_POSTNUM.NEXTVAL,'romantic_coding','YUMI','게시글입니다.3','3글 내용입니다.', 2, SYSDATE, '회원');
INSERT INTO FREEBOARD VALUES(FREE_POSTNUM.NEXTVAL,'romantic_coding','YUMI','게시글입니다.4','4글 내용입니다.', 1, SYSDATE, '회원');
INSERT INTO FREEBOARD VALUES(FREE_POSTNUM.NEXTVAL,'romantic_coding','YUMI','게시글입니다.5','5글 내용입니다.', 0, SYSDATE, '회원');

SELECT * FROM FREEBOARD;


DELETE FROM FREEBOARD;