DROP TABLE NOTICE;
DROP SEQUENCE NOTICESEQ;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICE(
NOTICE_POSTNUM NUMBER PRIMARY KEY,
NOTICE_WRITER VARCHAR2(500) NOT NULL,
NOTICE_TITLE VARCHAR2(500) NOT NULL,
NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
NOTICE_REGDATE DATE NOT NULL,
NOTICE_VIEWS NUMBER
);

SELECT * FROM NOTICE;

INSERT INTO NOTICE VALUES (NOTICESEQ.NEXTVAL, '신은정','TEST', 'TEST1234',SYSDATE,0);
