DROP TABLE NOTICEBOARD;
DROP SEQUENCE NOTICESEQ;

CREATE SEQUENCE NOTICESEQ;

CREATE TABLE NOTICEBOARD(
NOTICE_POSTNUM NUMBER PRIMARY KEY,
MEMBER_ID VARCHAR2(500) NOT NULL,
NOTICE_TITLE VARCHAR2(500) NOT NULL,
NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
NOTICE_REGDATE DATE NOT NULL,
NOTICE_VIEWS NUMBER
);

SELECT * FROM NOTICEBOARD;

SELECT NOTICE_REGDATE FROM NOTICEBOARD WHERE NOTICE_POSTNUM=1;

SELECT * FROM NOTICEBOARD ORDER BY NOTICE_REGDATE DESC;

SELECT ROWNUM,X.* FROM(SELECT * FROM NOTICEBOARD ORDER BY NOTICE_REGDATE DESC)X WHERE ROWNUM<4;

INSERT INTO NOTICEBOARD VALUES (NOTICESEQ.NEXTVAL, 'admin','TEST', 'TEST1234',SYSDATE,0);
INSERT INTO NOTICEBOARD VALUES (NOTICESEQ.NEXTVAL, 'admin','TEST', 'TEST1234',SYSDATE,0);

INSERT INTO NOTICEBOARD VALUES (NOTICESEQ.NEXTVAL, 'admin','게시글12', 'TEST1234',SYSDATE,0);
INSERT INTO NOTICEBOARD VALUES (NOTICESEQ.NEXTVAL, 'admin','게시글34', 'TEST1234',SYSDATE,0);
