DROP TABLE RESERVATION;

CREATE SEQUENCE RESERVATIONSEQ;

SELECT * FROM RESERVATION;

CREATE TABLE RESERVATION(
	RESERVATIONSEQ NUMBER NOT NULL,
	DAYOFWEEK VARCHAR2(100) NOT NULL,
	RES_REGDATE DATE,
	ORDER_STATUS VARCHAR2(10) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_ID VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(500) NOT NULL,
	MEMBER_LEVEL VARCHAR2(50) NOT NULL,
	DOSIRAK_TITLE VARCHAR2(2000),
	DOSIRAK_DELIVERY VARCHAR2(100) NOT NULL,
	DOSIRAK_PRICE NUMBER,
	DISH1 VARCHAR2(100),
	DISH2 VARCHAR2(100),
	DISH3 VARCHAR2(100),
	DISH4 VARCHAR2(100),
	DISH5 VARCHAR2(100),
	DISH6 VARCHAR2(100),
	DISH7 VARCHAR2(100),
	TAN NUMBER NOT NULL,
	DAN NUMBER NOT NULL,
	GI NUMBER NOT NULL,
	KCAL NUMBER NOT NULL,
	CUSTOM_STATUS VARCHAR2(2) NOT NULL
);

SELECT * FROM reservation;

SELECT TO_CHAR(SYSDATE,'d') FROM DUAL;

SELECT to_char((SELECT NOTICE_REGDATE FROM NOTICEBOARD WHERE NOTICE_POSTNUM=1),'d') FROM dual;

SELECT TO_DATE((SELECT NOTICE_REGDATE FROM NOTICEBOARD WHERE NOTICE_POSTNUM=1),'YYYYMMDD')
FROM DUAL; 

INSERT INTO RESERVATION VALUES(RESERVATIONSEQ.NEXTVAL,TO_CHAR(SYSDATE,'d'),
SYSDATE,'N','asdaldh@naver.com','aa','aa','USER','테스트','AM',4500,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,100,200,300,400,'N'
);