DROP TABLE UPLOAD_TABLE;
DROP SEQUENCE UPLOAD_SEQ;

CREATE SEQUENCE UPLOAD_SEQ;

CREATE TABLE UPLOAD_TABLE(
	UPLOAD_NO NUMBER NOT NULL PRIMARY KEY,
	DISH_NAME VARCHAR2(300) NOT NULL,
	DISH_TAN VARCHAR2(300) NOT NULL,
	DISH_DAN VARCHAR2(300) NOT NULL,
	DISH_ZI VARCHAR2(300) NOT NULL,
	DISH_AMOUNT VARCHAR2(300) NOT NULL,
	DISH_CAL VARCHAR2(300) NOT NULL,
	DISH_KIND VARCHAR2(300) NOT NULL,
	FILE_NAME VARCHAR2(500) NOT NULL,
	FILE_PATH VARCHAR2(4000) NOT NULL
);

SELECT * FROM UPLOAD_TABLE;